### ISSUE TITLE
Buttons in new card dialog

### ISSUE THREAD

**Issue by ghost** [fkinoshita/FlashCards#13]
The current dialog for adding a new card to a deck only has a button to close the dialog. It would be better to have a "Cancel" and a "Save" button, because that makes it clearer to the user what will happen when they press the button. Closing the dialog just with the button in the headerbar creates the impression that the user's input will not be saved.

**Comment by fkinoshita** [comment]
Hi, could you please test it now?

**Comment by ghost** [comment]
I thought of putting the buttons both in the top bar, the cancel button on the left and the save button on the right, but I guess the way you did it is also fine. @fkinoshita What do you think? If you want, I can also make a PR for what I described.
