### ISSUE TITLE
Clicking on a deck opens deck view

### ISSUE THREAD

**Issue by ghost** [fkinoshita/FlashCards#14]
Clicking on a deck should open the view of the deck and the cards it contains, not right away the practice mode.

Opening practice mode directly has the benefit that the user can't see the cards they start practicing, but it makes viewing the deck and adding cards kind of hard to find. Currently, you have to click on a deck, click the edit button in the bottom left, and close the edit dialog.

It would be much more intuitive if clicking on a deck takes you to the deck view, which should contain a "Practice" button that starts practice mode.

**Comment by fkinoshita** [comment]
You should be able to edit a deck clicking on the edit icon next to it, I guess having it go to practice mode right away is better for regular use, making it go to deck view everytime would be annoying.

**Comment by ghost** [comment]
> You should be able to edit a deck clicking on the edit icon next to it, I guess having it go to practice mode right away is better for regular use, making it go to deck view everytime would be annoying.

Oh, I didn't know that about the edit icon. I guess then it's not so much of an issue.

**Comment by fkinoshita** [comment]
Closing this then! :)
